export const ADDPRODUIT = 'ADDPRODUIT';
export const DELETEPRODUIT = 'DELETEPRODUIT';
export const LISTEADDPRODUIT = 'LISTEADDPRODUIT';
export const LISTEADDPRODUITFAIL = 'LISTEADDPRODUITFAIL';
export const LISTEDELETEPRODUIT = 'LISTEDELETEPRODUIT';
export const ADDPRODUITSTODATA = 'ADDPRODUITSTODATA';
export const ADDPRODUITSTODATAERROR = 'ADDPRODUITSTODATAERROR';
export const DELETEPRODUITSFROMDATASUCC = 'DELETEPRODUITSFROMDATASUCC';
